# Generated by Django 3.2.9 on 2021-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='coordinates',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.TripCoordinates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trip',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Trip'),
        ),
    ]
