# Generated by Django 3.2.9 on 2021-11-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='trip',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='markers',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.MarkerCoordinate'),
        ),
        migrations.AlterField(
            model_name='markercoordinate',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
