# Generated by Django 3.2.5 on 2021-07-12 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='uniq_key',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subanswer',
            name='uniq_key',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
