# Generated by Django 3.2.5 on 2021-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0003_auto_20210712_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_created_date',
            field=models.DateTimeField(verbose_name='Дата создания формы'),
        ),
    ]
