# Generated by Django 3.2.5 on 2021-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0004_alter_form_form_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания формы'),
        ),
    ]
