# Generated by Django 3.2.5 on 2021-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0005_alter_form_form_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
