# Generated by Django 3.2.5 on 2021-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_comment',
            field=models.BooleanField(default=False, verbose_name='Наличие комментария'),
        ),
    ]
