# Generated by Django 3.2.5 on 2021-07-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0007_question_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uniq_key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
