# Generated by Django 3.2.5 on 2021-07-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0008_question_uniq_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='create_vote.question'),
            preserve_default=False,
        ),
    ]
