# Generated by Django 3.2.5 on 2021-07-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0009_subanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subanswer',
            name='value',
            field=models.CharField(max_length=300, verbose_name='Связанный ответ'),
        ),
    ]
