# Generated by Django 3.2.5 on 2021-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0010_alter_subanswer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='sub_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Группа'),
        ),
    ]
