# Generated by Django 3.2.5 on 2021-07-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0011_auto_20210717_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='SubAnswer',
        ),
    ]
