# Generated by Django 3.2.5 on 2021-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0013_form_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='uniq_key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
