# Generated by Django 3.2.5 on 2021-07-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0014_form_uniq_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=50, verbose_name='Ответ')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_vote.form', verbose_name='Форма')),
            ],
        ),
    ]
