# Generated by Django 3.2.5 on 2021-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0015_sendedform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendedform',
            name='form',
        ),
        migrations.AddField(
            model_name='sendedform',
            name='form_key',
            field=models.CharField(default=1, max_length=50, verbose_name='Ключ формы'),
            preserve_default=False,
        ),
    ]
