# Generated by Django 3.2.9 on 2021-11-01 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0018_sendedcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='group',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.CharField(max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Слишком короткое имя формы'), django.core.validators.MaxLengthValidator(500, message='Слишком длинное имя формы')], verbose_name='Название формы'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4, message='Слишком короткий пароль к результатам')], verbose_name='Пароль к результатам'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.CharField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, message='Слишком длинное описание вопроса')], verbose_name='Описание вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(4, message='Слишком короткий заголвок вопроса'), django.core.validators.MaxLengthValidator(500, message='Слишком длинный заголовок вопроса')], verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='sendedcomments',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='sendedcomments',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='sendedform',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
    ]
