# Generated by Django 3.2.9 on 2021-11-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0020_auto_20211102_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='is_comment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
