# Generated by Django 3.2.9 on 2021-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0021_alter_questiontable_is_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtable',
            name='enter_code',
            field=models.IntegerField(default=0),
        ),
    ]
