# Generated by Django 3.2.9 on 2021-11-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0022_formtable_enter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtable',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='formtable',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
