# Generated by Django 3.2.9 on 2021-11-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0023_auto_20211102_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFormTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.answerstable')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.formtable')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.groupstable')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.questiontable')),
            ],
        ),
    ]
