# Generated by Django 3.2.9 on 2021-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0024_sendformtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendformtable',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
