# Generated by Django 3.2.9 on 2021-11-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0027_formtable_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFormCommentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.sendformtable')),
            ],
        ),
    ]
