# Generated by Django 3.2.9 on 2021-11-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_vote', '0028_sendformcommentstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendformcommentstable',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='create_vote.questiontable'),
            preserve_default=False,
        ),
    ]
